name: oc-lettings - Lint - Test - Build - Push

on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'
      - 'chore/**'
      - 'refactor/**'
      - 'hotfix/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8

      - name: Run pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)
          echo "COMMIT_TAG=matt13290/oc-lettings:${SHORT_SHA}" >> $GITHUB_ENV
          echo "LATEST_TAG=matt13290/oc-lettings:latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.COMMIT_TAG }}
            ${{ env.LATEST_TAG }}

  deployment:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
