name: oc-lettings - Lint - Test - Build - Push

on:
  push:
    branches:
      - 'feat/**'
      - 'bug/**'
      - 'chore/**'
      - 'refactor/**'
      - 'hotfix/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8

      - name: Run pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker image tags
        id: vars
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/oc-lettings
          COMMIT_SHA=${{ github.sha }}
          BRANCH_NAME=${GITHUB_REF_NAME//\//-}  # replace '/' with '-' for valid tag names

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "COMMIT_TAG=$IMAGE_NAME:$BRANCH_NAME-$COMMIT_SHA" >> $GITHUB_ENV
          echo "LATEST_TAG=$IMAGE_NAME:$BRANCH_NAME-latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.COMMIT_TAG }}
            ${{ env.LATEST_TAG }}
